name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  pr-fuzzing:
    name: Fuzz (PR, ${{ matrix.sanitizer }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: code-change
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
      - name: Upload SARIF to GitHub Security tab
        if: always() && steps.build.outcome == 'success'
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        with:
          sarif_file: cifuzz-sarif/results.sarif
          checkout_path: cifuzz-sarif
